{
 "title": "Dell PowerEdge R640 iDrac Server",
 "description": "Dell PowerEdge R640 iDrac \r\n\r\nDatasource = Zabbix.\r\n\r\nMétricas:\r\nCpu.\r\nMemory\r\nRaid\r\nDISK S.M.A.R.T\r\nMemória RAM Status\r\nICMP\r\nConsumo Watts\r\nVoltages\r\nFan\r\nTemperatura\r\nInterfaces\r\nPSU\r\nUptime\r\nControladora\r\nCMOS Battery",
 "tags": [
  "Servidor",
  "Dell",
  "iDrac"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {}
   },
   {
    "name": "hypervbd",
    "query": {}
   },
   {
    "name": "FAN_query",
    "label": "FAN",
    "query": {}
   },
   {
    "name": "disk",
    "label": "disk",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Servidor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "Dell iDRAC: Hardware model name"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "schema": 12,
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "PowerEdge R640",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": {
    "content": "<img src=\"https://i.dell.com/sites/csimages/App-Merchandizing_Images/all/oc_image_r660xs_server_rack.png\" height=\"100px\" width=\"100%\">\n\n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "iDrac Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "DRAC Firmware version" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "schema": 12,
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Uptime" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Dell iDRAC: Uptime (network)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "STATUS" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "Dell iDRAC: Overall system health status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CMOS BATERIA" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "CMOS Battery Status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PS1 FONTE" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "PS1 Status: Power supply status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PS2 FONTE" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "PS2 Status: Power supply status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "INTERFACES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "NIC 1" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "NIC 1 : Connection Status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "NIC 2" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "NIC 2 : Connection Status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "NIC 3" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "NIC 3 : Connection Status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "NIC 4" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "NIC 4 : Connection Status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CONTROLADORA",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "Integrated RAID Controller 1: Disk array controller model"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "schema": 12,
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "System Asset Tag" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "schema": 12,
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Temperature Sensor (.*) Temp Value/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ping" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Dell iDRAC: ICMP ping" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "RAID STATUS" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Disk 1(VOLUME0_RAID10): Status" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "LAYOUT RAID" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "Disk 1(VOLUME0_RAID10): Layout type"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CONTORLADORA STATUS" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "Integrated RAID Controller 1: Disk array controller status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "LAYOUT RAID" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "Disk 1(VOLUME0_RAID10): Layout type"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "S.M.A.R.T. ",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Solid State Disk .*: Physical disk S.M.A.R.T. status/"
     },
     "itemTag": { "filter": "" },
     "limit": "1",
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "CPU TEMP",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Temperature Sensor (.*) Temp Value/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Latência",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ping" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Dell iDRAC: ICMP response time" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "TIPO",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Solid State Disk (.*): Physical disk media type/"
     },
     "itemTag": { "filter": "" },
     "limit": "1",
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "RPM FAN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "/Fan System Board Fan.*Speed/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Loss ICMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ICMP Latência" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Dell iDRAC: ICMP loss" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Latência ICMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ICMP Latência" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Dell iDRAC: ICMP response time" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "ICMP Latência" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Dell iDRAC: ICMP ping" },
     "itemTag": { "filter": "component: network" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "TAMANHO",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Solid State Disk (.*): Disk size/"
     },
     "itemTag": { "filter": "" },
     "limit": "1",
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Consumo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PS1" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Power Supply 1 State Settings" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    },
    {
     "alias": "CPU 1 Temp",
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "PS2" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "Power Supply 2 State Settings" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Memory RAM  Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Memory Slot DIMM.Socket.(.*) Status/"
     },
     "itemTag": { "filter": "" },
     "limit": "1",
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": {
      "filter": "/Memory Slot DIMM.Socket.(.*) Size/"
     },
     "itemTag": { "filter": "" },
     "limit": "1",
     "macro": { "filter": "" },
     "measurement": "idrac-hosts",
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ],
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "VOLTAGE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "Hyper-V SRV-BD" },
     "item": { "filter": "/Voltage : (.*) PG Status/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}